image: eclipse-temurin:21

stages:
  - build
  - changelog

include:
  - remote: 'https://gitlab.com/g3476/cliffhanger/-/raw/main/gitlab-ci/cliffhanger.yml'

build:
  only:
    - tags
  stage: build
  script: >
    ./gradlew build &&
    ./gradlew publish
  artifacts:
    expire_in: 30 days
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
